"""Add Class model

Revision ID: 2598e9581e10
Revises: 0e4572866b19
Create Date: 2025-08-16 23:13:45.355625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2598e9581e10'
down_revision = '0e4572866b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    # ### end Alembic commands ###
